# Generated by Django 4.2.5 on 2023-12-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSbayStore', '0002_product_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
