# Generated by Django 4.2.5 on 2023-12-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSbayStore', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
