# Generated by Django 4.2.5 on 2024-01-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSbayStore', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, default='defaultavatar.jpeg', null=True, upload_to='Avatar/'),
        ),
    ]
